### ISSUE TITLE
Ability to resume conversion if conversion fails at some point

### ISSUE THREAD

**Issue by philipstarkey** [chrisjbillington/hg-export-tool#2]
When converting a large number of repositories, it's really annoying if it crashes part way through as you either need to edit the repo_mapping.json file to remove the ones already converted (difficult if using Python 2.7 as it doesn't preserve the dictionary order in the JSON file) or delete all the converted repositories (which is a waste of time!)

**Comment by chrisjbillington** [comment]
Cool, I'll make it do the conversion to a temporary directory and then copy to the real destination if successful. If a repo already exists, it'll just skip it and print a warning. That way you'll be able to resume, but there won't be any half-converted repos lying around.

**Comment by chrisjbillington** [comment]
Done
